### ISSUE TITLE
Add container objects.

### ISSUE THREAD

**Issue by drwhut** [drwhut/open-tabletop#27]
**Is your feature request related to a problem? Please describe.**
Right now, there is no way to represent pieces being put into an opaque container, which is a requirement for a lot of board games.

**Describe the solution you'd like**
Add the ability to import and spawn "containers". They should:
* Be able to have pieces added to them by detecting collisions with other pieces on one of it's sides.
* Hide the pieces once they have been added to the container.
* Be able to randomly remove pieces when fast-dragging.

**Describe alternatives you've considered**
This could be theoretically done with hidden areas (#13), but the benefit of containers is that since they are game pieces, you could drag them around the table.

**Additional context**
None.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
There should be a way to see inside of them and pick out a specific object
