### ISSUE TITLE
git submodule version issue resulting in freezing on opening screen with error: Nonexistent function 'copy_file' in base 'TabletopImporter'

### ISSUE THREAD

**Issue by JJones780** [drwhut/open-tabletop#328]
### but is still being called in the Tabletop Club Godot project.

Compiling the Godot fork (  3.5.3 and 3.6 )
Importing and running TableTop Club results in error: Nonexistent function 'copy_file' in base 'TabletopImporter'

\
**To Reproduce**
Follow Linux steps on website to download and  compile custom Godot. Download TableTop Club  and import into custom Godot and run it.

**Expected behavior**
a running TableTop Club

**Environment**
Linux

**Version**
0.1, 0.2,       with compiles of Godot forks 3.5.3 and , 3.6 ( and more?)

**Additional context**

**the copy_file function has been removed from the tabletop_club_godot_module**
_all versions (? checked 3.5.3 and 3.6)  of  forked Godot point module here: https://github.com/drwhut/tabletop_club_godot_module/tree/9695edf45f23e34813371f9f18406dd48f633e40
V3.4 still points to version with copy_file function but not retrieved automatically. 

**but is still being called in all(?) versions of the Tabletop Club Godot project.**
_search for copy_file in all branches of  https://github.com/drwhut/tabletop-club/blob/0.2-rewrite/game/Scripts/AssetDB.gd_

**WORKAROUND:**
look up how to set the submodule version and re-get using git or manually:
remove existing      `godot/modules/tabletop_club_godot_module`
download [ tabletop_club_godot_module 3.4](https://github.com/drwhut/tabletop_club_godot_module/tree/3.4) 
Expand, rename from` tabletop_club_godot_module-3.4`   to  ` tabletop_club_godot_module`
 and copy into the `godot/modules/`  in place of the directory removed above.
With this workaround all works well.

**Comment by drwhut** [comment]
The branch you compile depends on which version of Tabletop Club you want to use:

* For v0.1.3, you need to compile `tabletop-3.4.5`.
* For `0.2-rewrite`, you need to compile `tabletop-3.6`.

The `copy_file` function is used by v0.1.x only, it was removed for v0.2.0 after re-writing the custom `TabletopImporter` class.

Ensure that you are compiling the right branch of the fork for the version of the game you want to use, and let me know if it works :+1:

**Comment by JJones780** [comment]
Yes, I tried a few versions. 
It looks like the problem is that the 0.2 rewrite still refers to copy_file
 ( and also the website version table is out of date ).

I did try 0.2rewrite + 3.6 and it doesn't work.
I also tried 0.2rewrite + 3.5.3 and it doesn't work. 
I hadn't tried  0.1.3 + 3.4.5 bt it looks like that should work - see links below for these combinations.

**website version table:**
It looks like the [website](https://docs.tabletopclub.net/en/stable/general/download/compiling_from_source.html)  needs to be updated to the [latest 3.6 info](https://github.com/drwhut/tabletop-club/blob/master/docs/general/download/compiling_from_source.rst) .

**0.2rewrite still refers to copy_file():**
I looked through the various branches: master, v0.1.3 AND 0.2-rewrite all have  references to the TabletopImporter->copy_file() function  in lines  1361, 1361 and  1348 of [Scripts/AssetDB.gd](https://github.com/drwhut/tabletop-club/blob/0.2-rewrite/game/Scripts/AssetDB.gd) respectively.

**Or change godot versions to point to copy_file() enabled submodules:**
If you click on the tabletop_club_module in the following links:
[ 3.5.3](https://github.com/drwhut/godot/tree/tabletop-3.5.3/modules)  does NOT point to a version with copy_file()
[3.6](https://github.com/drwhut/godot/tree/tabletop-3.6/modules)  does NOT point to a version with copy_file()
[3.4.5 ](https://github.com/drwhut/godot/tree/tabletop-3.4.5/modules)DOES point to a version with the copy_file() !

I hope I've included enough info in a clear way... that or I drowned it out! ;)
Thanks for your efforts working on this... I look forward to using it to help my group of friends play online in the depths of a coming Canadian winter ;)

**Comment by drwhut** [comment]
Ah okay, I think I get the confusion now...

> It looks like the problem is that the 0.2 rewrite still refers to copy_file

As you've found out, this is `Scripts/AssetDB.gd`. However, it is safe to ignore all errors and warnings from the `Scenes/` and `Scripts/` folders in the `0.2-rewrite` branch, as these two folders are not used in the re-write at all. I've only kept them in the git tree so that I can refer back to the old v0.1.x code without needing to `git stash` and `git checkout` each time.

> It looks like the [website](https://docs.tabletopclub.net/en/stable/general/download/compiling_from_source.html) needs to be updated to the [latest 3.6 info](https://github.com/drwhut/tabletop-club/blob/master/docs/general/download/compiling_from_source.rst) .

It has been, you just need to switch from the `stable` version of the documentation to the `latest` version, using the ReadTheDocs widget in the bottom-left hand corner.

So yeah, in summary, the custom module used to have a function called `copy_file` that the v0.1.x versions of the game still use. However, for v0.2.0, I decided to re-write the custom module and make it a lot more generic, and I moved the `copy_file` function from C++ to GDScript in the process, which is why in v0.2.0 it is no longer called (that is, in the *new* AssetDB, located at `assets/asset_db.gd`). But for compatibility I had to reference a specific commit of the custom module for v0.1.x, since it expects the `TabletopImporter::copy_file` function to exist.

**Comment by JJones780** [comment]
No worries....
My 0.2rewrite gets stuck at 0% importing assets without the copy_file function module version. I'm sure it'll clear up soon.
It's not holding me up.... I'm doing some preliminary investigation into adding VR as I find the time.
