### ISSUE TITLE
Support custom objects with emissive materials.

### ISSUE THREAD

**Issue by drwhut** [drwhut/open-tabletop#34]
**Is your feature request related to a problem? Please describe.**
When exporting models using Blender, you can export models with emissive materials, meaning that they should emit light in the scene. However, when importing them into the game, the emissive material does not affect the environment around it.

**Describe the solution you'd like**
Support emissive materials by having them light the environment around them.

**Describe alternatives you've considered**
None.

**Additional context**
This may only be able to be supported when Godot has dynamic real-time global illumination, which is planned to come with the 4.0 release, see [here](https://godotengine.org/article/godot-40-gets-sdf-based-real-time-global-illumination).

**Comment by 20kdc** [comment]
Idea: rather than using actual emissive materials, consider approximating it with an OmniLight or SpotLight, and then applying the emission to the material?
