### ISSUE TITLE
Should the ability to lay stacks on the table automatically be added?

### ISSUE THREAD

**Issue by drwhut** [drwhut/open-tabletop#4]
**Is your feature request related to a problem? Please describe.**
It's tedious to take e.g. a stack of cards and lay them nicely on the table in a line such that each card slightly overlaps the previous card.

**Describe the solution you'd like**
Have a button added to the context menu of a stack to lay the stack automatically.

**Describe alternatives you've considered**
None.

**Additional context**
The reason this is an open question is that part of me thinks this is a very niche feature that would rarely be used.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
I think it would be a useful feature but i think i personally use it for aesthetic than anything remotely used for gameplay

**Comment by drwhut** [comment]
After (finally) having some discussions about the feature, I've concluded that while it would be a convenient feature to have, it's use cases are very few and far between. Plus, the context menu for decks of cards/tokens is already quite big, so it would also make the menu too big.

The reason this feature was suggested in the first place is that players found it difficult at the time to move decks of cards around, but once players got used to the grab mechanic, laying out cards on the table became quite easy (if anything, it's just a bit time consuming, depending on the number of cards).

I can obviously re-open this issue if the feature is requested again, but for now, I don't think this functionality is necessary.
