### ISSUE TITLE
How about zerotier based p2p networking?

### ISSUE THREAD

**Issue by traverseda** [drwhut/open-tabletop#54]
https://github.com/zerotier/libzt

Seems like if you could get it implemented into the engine it would simplify a lot of things a great deal.

**Comment by drwhut** [comment]
I've been thinking about switching from dedicated servers to P2P networks w/ a host (since it would mean not having to host dedicated servers). I think Godot [already has something similar](https://docs.godotengine.org/en/stable/tutorials/networking/webrtc.html) to ZeroTier, but I'll give it a closer look tomorrow to see if it's worth adding it as a Godot module (maybe one already exists?). Thank you for the suggestion!

**Comment by traverseda** [comment]
Well that has the advantage of working in a web browser, which I suppose could be a pretty big advantage. Not sure how asset loading would work while running in a web browser though.

I think zerotier would likely be a lot more robust, and wouldn't require *any* extra infrastructure for initializing p2p connections, but it's not going to run in a web browser ever.

**Comment by drwhut** [comment]
> Well that has the advantage of working in a web browser, which I suppose could be a pretty big advantage. Not sure how asset loading would work while running in a web browser though.

Yeah, due to the way asset loading works, it's pretty much impossible to get the game working on the web.

> I think zerotier would likely be a lot more robust, and wouldn't require _any_ extra infrastructure for initializing p2p connections, but it's not going to run in a web browser ever.

After doing a bit of research, I noticed that in order to set it up so you don't need any extra infrastructure, you need to use their in-house hosting, which in the free tier only allows up to [50 members at once](https://www.zerotier.com/pricing/), and the next tier up is **$50/month**. Let me know if I'm misunderstanding their pricing, but that seems pretty extortionate!! So realistically, we would need to host our own infrastructure, and at that point, the only major difference I can think of between WebRTC and ZeroTier is that Godot comes with WebRTC support (for desktops, via the GDNative library), whereas it doesn't come with ZeroTier support (and no one has made a module for it as far as I can tell).

**Comment by traverseda** [comment]
Since this isn't going to run a web browser (the major disadvantage of using zerotier) I'll go in to a bit more detail about why I think it's potentially a better model. Of course godot not supporting it out of the box is certainly a problem and means that it might not be worth the time to port it to godot.

>Let me know if I'm misunderstanding their pricing, but that seems pretty extortionate!!

We'd almost definitely set it up as a [public network](https://www.zerotier.com/manual/#2_2_5) or ad-hoc network, which don't any any authorization/authentication and can have unlimited nodes for free.

So the big things with zerotier is it uses basically a public key to decide where to route things. That means everyone on the network get's an ipv6 ip address that doesn't change. Generally I think that zerotier is going to be a lot more robust then webrtc most of the time.

I think it practice you're going to find webrtc a lot more complicated. With webrtc you need an external signalling server to establish a new connection between peers every time. So that's a piece of infrastructure you're likely going to need an external server for, although I think it might be possible to hack something together using copy-pasted links as long as you don't mind needing to send someone a link to join a session every time.

Now under ideal conditions with webrtc you truly do operate p2p, but when that fails you need a TURN server to relay connections. I've found that zerotier is better about getting a direct p2p session going, but when it's not zerotier is currently offering free relay servers (a TURN server equivalent) and it's really easy to create your own relay server by specifying a host with a public ip address as a "moon" which makes it act as the webrtc equivalent of a SIP/STUN/TURN server. Trying to set up your own SIP/ICE/STUN/TURN functionality under zerotier is a few commands, trying to set it up for webrtc is a giant pain.

Under zerotier I'm imagining that ipv6 address acting as a sort of "friend code" to uniquely identify a user. You can send an invite by basically just pinging someone based on their zerotier address, you could make assets available in the background sort of like torrents if you were so inclined.

Personally I think zerotier would make the networking a lot simpler, there would be some initial fighting with it at the start but once it's in place it's a *whole* lot simpler then webrtc. Making a GDNative library for it would be challenging though I'm sure.

**Comment by traverseda** [comment]
I think the packet quality-of-service rules would also be quite useful if you ever wanted  to include things like VOIP chat.

My dream is that something like this works as a wayland compositor, allowing you to drop real (network transparent) apps into an open-tabletop server. That's probably not going to happen, but it would be amazing to drop a web browser into a server and all be able to watch the same videos, or drop a libreoffice instance and all be able to edit the same spreadsheet.

That's obviously not going to happen any time soon, but QoS would help with stuff like that, and the port multiplexing of zerotier would help tremendously with multiple streams.

**Comment by drwhut** [comment]
Ah, you've got some interesting points! I've got a few questions, though:

* When you say ZeroTier offer free TURN-server equivalents, do you mean they host some that you can use for free, or are you able to get them for free and then host them yourself?
* What makes setting up a ZeroTier relay server easier than setting up a WebRTC STUN/TURN server? As far as I'm aware for STUN/TURN servers, you just start them and use them? ([here](https://www.npmjs.com/package/node-turn) is an example of a TURN server I was sent that seems like you just run a command to start it)
* My idea for how the matchmaking was going to work was by having the host generate a four-letter room code for their instance, and they can set the game to be either public (the instance is publically broadcast in a server list), or private (other players *need* to know the room code to join). How would you see this sort of matchmaking working with ZeroTier?
* How much support is there for ZeroTier? As in, if I were to run into a problem with ZeroTier that I didn't know how to fix, how likely is it that I find the solution online without having to make my own post?

**Comment by traverseda** [comment]
* They host them for free, and they/ve always been high enough bandwidth that I've never had to think about it. They also make it easy to host them yourself.
 * Any zerotier client can be what they call a "moon" which handles the entire TURN stack. Marginally easier because that functionality is integrated into the library or client daemon. Basically there's one static executable that lets you build an entire zerotier network in whatever topology you want. Well everything except for the GUI that runs on my.zerotier.com, but we don't need that and there are [FOSS alternatives](https://key-networks.com/ztncui/#screenshots).
 * I'd imagine it being sort of like a friend code. You send somebody what is basically an ipv6 address, then they get added to your friend list. Then it would work pretty much like matchmaking on steam. Because you can directly access your friends based on ipv6 address that lets you do stuff like query them for their preferred name/profile-picture, start a chat, etc. I think set ipv6 "friend codes" would also make it a lot easier to host game assets in the background, possibly with something distributed and torrent-alike. It also makes it so that residential internet customers can host permanent rooms in some kind of server browser.
 * I haven't worked with the library (libzt) a lot, but the zerotier documentation is quite good and I haven't really run into anything I'd call an issue. It's got a pretty reasonable community. I'd hesitate to call it rock solid, but the only issues I've ever had with it (the daemon version) were related to the environment I was running it in. A cellphone network with weird UDP traffic-shaping rules, a NAS that decided to remove all the routes I added to the kernels routing table, etc. Other then that it just sort of works. The library is pretty new though, and comparatively untested. I've found the developers to be quite responsive, although clearly busy and with their own priorities.

**Comment by drwhut** [comment]
Sorry it's been a while since I've replied in this thread, I've been busy the past few weeks with university work.

I've considered all of your points, and the way I see it is that ZeroTier might be the more 'elegant' solution, but would require more work to get running than WebRTC (which is officially supported by Godot). So on that basis, I'm going to try implementing WebRTC first, and if I find that it's not up to the job, then I will consider using ZeroTier.

**Comment by traverseda** [comment]
Makes sense, I just wanted to make you aware of zerotier in case it did end up being useful for you. Good luck!
