### ISSUE TITLE
Duplicate project name

### ISSUE THREAD

**Issue by Rundik** [drwhut/open-tabletop#58]
There is already a tabletop simulator named Open Tabletop - https://github.com/Rundik/OpenTabletop

**Comment by drwhut** [comment]
Thank you for bringing this to my attention - I've got a question though (since you're the owner of the project): the last commit to your project was on the 1st May 2019, and the last release was on the 9th Jan 2017. Do you have any intentions to keep working on the project?

**Comment by Rundik** [comment]
Actually yes, I wanted to make the next iteration of the project this year

**Comment by drwhut** [comment]
What do you plan to do with the project?

**Comment by Rundik** [comment]
I'm planning to make it fully decentralized and probably in 3d (not sure yet if I want it in 3d). So the name is kind of important for me

**Comment by drwhut** [comment]
When I first created the project in June of 2020, I did check to see if the name was taken at the time - I saw your project, but at the time it was not updated in over a year, and I genuinely thought you had abandoned it.

I'm at a loss as to why either of us should "claim" the name OpenTabletop, seeing as both of our projects are open source, and neither of us have trademarked the name. Furthermore, there are two other projects also called OpenTabletop (see https://github.com/mini-mammoth/opentabletop and https://github.com/treeman0013/OpenTabletop).

With that being said, I'd happily consider renaming my project if you complete yours first. With the way my project's infrastructure is set up, it would be a pain to rename all of the repositories/dependencies at this point.

**Comment by Rundik** [comment]
My project was complete 3 years ago already. It is fully functional and being used. I don't get it why you need updates from me. It's just a little awkward when two projects with the same purpose have the same name.
That two other projects were created in 2020 and 4 days ago

**Comment by drwhut** [comment]
OK, I don't get why you've only asked me to change this project's name and not the others, but I'll change mine in due course.

**Comment by Rundik** [comment]
Thanks a lot, I really appreciate that
